import {
  construction_icon,
  design_icon,
  DesignPlanning1Img1,
  DesignPlanning1Img2,
  DesignPlanning1Img3,
  DesignPlanning2Img1,
  DesignPlanning2Img2,
  DesignPlanning2Img3,
  DesignPlanning2Img4,
  DesignPlanning3Img1,
  DesignPlanning3Img2,
  DesignPlanning3Img3,
  DesignPlanning4Img1,
  DesignPlanning4Img2,
  DesignPlanning4Img3,
  DesignPlanning5Img1,
  DesignPlanning5Img2,
  DesignPlanning5Img3,
  DesignPlanning5Img4,
  DesignPlanning6Img1,
  DesignPlanning6Img2,
  DesignPlanning6Img3,
  DesignPlanning6Img4,
  DesignPlanning6Img5,
  DesignPlanning6Img6,
  DesignPlanning6Img7,
  DesignPlanning7Img1,
  DesignPlanning7Img2,
  DesignPlanning7Img3,
  DesignPlanning7Img4,
  DesignPlanning8Img1,
  DesignPlanning8Img2,
  DesignPlanning8Img3,
  DesignPlanning8Img4,
  DesignPlanning8Img5,
  DesignPlanning8Img6,
  DesignPlanning8Img7,
  DesignPlanning8Img8,
  DesignPlanning9Img1,
  DesignPlanning9Img2,
  DesignPlanning9Img3,
  DesignPlanning9Img4,
  DesignPlanning9Img5,
  DesignPlanning10Img1,
  DesignPlanning10Img2,
  DesignPlanning10Img3,
  DesignPlanning11Img1,
  DesignPlanning11Img2,
  DesignPlanning11Img3,
  DesignPlanning11Img4,
  DesignPlanning11Img5,
  DesignPlanning12Img1,
  DesignPlanning12Img2,
  DesignPlanning12Img3,
  Construction4Img1,
  Construction4Img2,
  Construction4Img3,
  Construction4Img4,
  Construction1Img1,
  Construction1Img2,
  Construction1Img3,
  Construction2Img1,
  Construction2Img2,
  Construction2Img3,
  Construction3Img1,
  Construction3Img2,
  Construction3Img3,
  Construction3Img4,
  Construction3Img5,
  Construction3Img6,
  Construction3Img7,
  Courses1Img1,
  Courses1Img2,
  Courses1Img3,
  Courses1Img4,
  Courses2Img1,
  Courses2Img2,
  Courses2Img3,
  Courses3Img1,
  Courses3Img2,
  Courses3Img3,
  Courses4Img1,
  Courses4Img2,
  Courses5Img1,
  Courses5Img2,
  Courses6Img1,
  Courses6Img2,
  course_icon,
} from "../constants/Data";

const GalleryData = [
  {
    id: 1,
    imageUrl: DesignPlanning1Img1,
    title: "Design & Planning",
    description: "Immersive 3D View of chunnakam House Designed by Us",
    icon: design_icon,
    images: [DesignPlanning1Img1, DesignPlanning1Img2, DesignPlanning1Img3],
  },
  {
    id: 2,
    imageUrl: Construction1Img2,
    title: "Construction",
    description:
      "In the design and construction of our company, a dream house is being built in Mallakam",
    icon: construction_icon,
    images: [Construction1Img1, Construction1Img2, Construction1Img3],
  },
  {
    id: 3,
    imageUrl: Courses1Img1,
    title: "Courses",
    description:
      "Revit Architecture 3D Visualization & VR Training for Students and Trainees",
    icon: course_icon,
    images: [Courses1Img1, Courses1Img2, Courses1Img3, Courses1Img4],
  },
  {
    id: 4,
    imageUrl: DesignPlanning2Img1,
    title: "Design & Planning",
    description:
      "3D Modeling for  Inuvil House Designed by Experienced Architects",
    icon: design_icon,
    images: [
      DesignPlanning2Img1,
      DesignPlanning2Img2,
      DesignPlanning2Img3,
      DesignPlanning2Img4,
    ],
  },
  {
    id: 5,
    imageUrl: Construction2Img1,
    title: "Construction",
    description:
      "Design and construction by J-A-D (Jaffna Architectural Designers).Three houses located in Kilinochchi area in our design and construction.",
    icon: construction_icon,
    images: [Construction2Img1, Construction2Img2, Construction2Img3],
  },
  {
    id: 6,
    imageUrl: Courses2Img1,
    title: "Courses",
    description: "Diploma In Architectural Design awarding ceremony",
    icon: course_icon,
    images: [Courses2Img1, Courses2Img2, Courses2Img3],
  },
  {
    id: 7,
    imageUrl: DesignPlanning3Img1,
    title: "Design & Planning",
    description: "3D House Modeling project for our valued client presentation",
    icon: design_icon,
    images: [DesignPlanning3Img1, DesignPlanning3Img2, DesignPlanning3Img3],
  },
  {
    id: 8,
    imageUrl: Courses3Img1,
    title: "Courses",
    description: "Virtual Reality Training for our Future Architects",
    icon: course_icon,
    images: [Courses3Img1, Courses3Img2, Courses3Img3],
  },
  {
    id: 9,
    imageUrl: DesignPlanning4Img1,
    title: "Design & Planning",
    description:
      "the Stunning 3D Vision of Mr. Guna's Home, Crafted by Our Architects.",
    icon: design_icon,
    images: [DesignPlanning4Img1, DesignPlanning4Img2, DesignPlanning4Img3],
  },
  {
    id: 10,
    imageUrl: Courses4Img1,
    title: "Courses",
    description:
      "VR Training with Practical Learning for Our Students and Trainees",
    icon: course_icon,
    images: [Courses4Img1, Courses4Img2],
  },
  {
    id: 11,
    imageUrl: DesignPlanning5Img1,
    title: "Design & Planning",
    description:
      "the Stunning 3D Vision of Mr. Guna's Home, Crafted by Our Architects.",
    icon: design_icon,
    images: [
      DesignPlanning5Img1,
      DesignPlanning5Img2,
      DesignPlanning5Img3,
      DesignPlanning5Img4,
    ],
  },
  {
    id: 12,
    imageUrl: Courses5Img1,
    title: "Courses",
    description:
      "Interior Design Classes with Practical Learning for Our Students ",
    icon: course_icon,
    images: [Courses5Img1, Courses5Img2],
  },
  {
    id: 13,
    imageUrl: Courses6Img1,
    title: "Courses",
    description: "Student Learning in the Revit Architecture at Our Center",
    icon: course_icon,
    images: [Courses6Img1, Courses6Img2],
  },
  {
    id: 14,
    imageUrl: Construction3Img1,
    title: "Construction",
    description:
      "The Amutha Theater located on Kandy Road, Vavuniya, was elegantly built by us (J-A-D)",
    icon: construction_icon,
    images: [
      Construction3Img1,
      Construction3Img2,
      Construction3Img3,
      Construction3Img4,
      Construction3Img5,
      Construction3Img6,
      Construction3Img7,
    ],
  },
  {
    id: 15,
    imageUrl: Construction4Img1,
    title: "Construction",
    description: "Our Drywall Basement Work",
    icon: construction_icon,
    images: [
      Construction4Img1,
      Construction4Img2,
      Construction4Img3,
      Construction4Img4,
    ],
  },
  {
    id: 16,
    imageUrl: DesignPlanning6Img1,
    title: "Design & Planning",
    description:
      "Three-dimensional view of the house designed by us in Velana.",
    icon: design_icon,
    images: [
      DesignPlanning6Img1,
      DesignPlanning6Img2,
      DesignPlanning6Img3,
      DesignPlanning6Img4,
      DesignPlanning6Img5,
      DesignPlanning6Img6,
      DesignPlanning6Img7,
    ],
  },
  {
    id: 17,
    imageUrl: DesignPlanning7Img1,
    title: "Design & Planning",
    description:
      "A three storied building was done by us for remedial work in Kilinochchi.",
    icon: design_icon,
    images: [
      DesignPlanning7Img1,
      DesignPlanning7Img2,
      DesignPlanning7Img3,
      DesignPlanning7Img4,
    ],
  },
  {
    id: 18,
    imageUrl: DesignPlanning8Img1,
    title: "Design & Planning",
    description:
      "A three-dimensional view of a traditional four-story house of Jaffna designed by us.",
    icon: design_icon,
    images: [
      DesignPlanning8Img1,
      DesignPlanning8Img2,
      DesignPlanning8Img3,
      DesignPlanning8Img4,
      DesignPlanning8Img5,
      DesignPlanning8Img6,
      DesignPlanning8Img7,
      DesignPlanning8Img8,
    ],
  },
  {
    id: 19,
    imageUrl: DesignPlanning9Img1,
    title: "Design & Planning",
    description:
      "3D view of vehicle sales platform designed by us in Kilinochchi.",
    icon: design_icon,
    images: [
      DesignPlanning9Img1,
      DesignPlanning9Img2,
      DesignPlanning9Img3,
      DesignPlanning9Img4,
      DesignPlanning9Img5,
    ],
  },
  {
    id: 20,
    imageUrl: DesignPlanning10Img1,
    title: "Design & Planning",
    description:
      "3D Rendering of a three-storied (Dilshan Trade Centre) showroom to be installed in Jaffna, designed by us.",
    icon: design_icon,
    images: [DesignPlanning10Img1, DesignPlanning10Img2, DesignPlanning10Img3],
  },
  {
    id: 21,
    imageUrl: DesignPlanning11Img1,
    title: "Design & Planning",
    description:
      "3D view of our design and construction two storey luxury house located in Vavuniya.",
    icon: design_icon,
    images: [
      DesignPlanning11Img1,
      DesignPlanning11Img2,
      DesignPlanning11Img3,
      DesignPlanning11Img4,
      DesignPlanning11Img5,
    ],
  },
  {
    id: 22,
    imageUrl: DesignPlanning12Img1,
    title: "Design & Planning",
    description: "The Kitchen Design by J-A-D",
    icon: design_icon,
    images: [DesignPlanning12Img1, DesignPlanning12Img2, DesignPlanning12Img3],
  },
];

export { GalleryData };
